### 校验测试，当 ID 为 Null 的时候
GET http://localhost:8081/validator/test?nickname=梁业锦
Accept: application/json

### 校验测试，当 size > 3 的时候
GET http://localhost:8081/validator/test?id=12&nickname=爱酱油不爱醋
Accept: application/json

### 校验测试，测试自定义 @Phone 注解
GET http://localhost:8081/validator/test?id=12&nickname=梁业锦&phone=1837873378800
Accept: application/json
